# 端口号配置
server:
  port: 8012

spring:
  application:
    name: provider-service
  datasource:
      name: test
      url: jdbc:mysql://127.0.0.1:3306/scbrl
      characterEncoding: utf8
      characterSetResults: utf8
      username: bruceliu
      password: bruceliu
      # druid 连接池配置
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  jpa:
    show-sql: true

# SQL日志打印
logging:
  level:
    com:
      scbrl: DEBUG

# MyBatis 配置 注：1.2.0版本会出现冲突，pom需配置成1.2.2
mybatis:
  check-config-location: true
  configuration:
    call-setters-on-nulls: true

# Eureka配置 发现注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://15959276686:bruceliu@127.0.0.1:8000/eureka/
