# 端口号配置
server:
  port: 8000

# Eureka配置
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/

# 安全认证的配置
security:
  basic:
    enabled: true
  user:
    name: 15959276686
    password: bruceliu